apiVersion: v1
kind: PersistentVolume
metadata:
  name: pers-vol
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pers-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pers-vol
  resources:
    requests:
      storage: 1Gi
