apiVersion: batch/v1
kind: Job
metadata:
  name: loadgeneration
spec:
  template:
    metadata:
      name: loadgeneration
    spec:
      containers:
      - name: loadgeneration
        image: eginez/loadgeneration
        imagePullPolicy: Always
        env:
          - name: TODOSERVICE_HOST
            value: "todo-service"
          - name: TODOSERVICE_PORT
            value: "8443"
          - name: LOADTESTS_RESULTS
            value: "/tmp/results"

      restartPolicy: Never
