FROM container-registry.oracle.com/graalvm/native-image:23-muslib AS nativebuild
WORKDIR /build
# Build a statically linked native executable optimizing for size with `-Os`
RUN native-image -Os --static --libc=musl -m jdk.httpserver -o jwebserver.static
RUN ls -lh jwebserver.static

FROM alpine:3
COPY --from=nativebuild /build/jwebserver.static /
COPY index.html /web/index.html
EXPOSE 8000
ENTRYPOINT ["/jwebserver.static", "-b", "0.0.0.0", "-d", "/web"]
