library(lattice)
data <<- numeric(100)

function(dataHolder) {
    svg()
    data <<- c(data[2:100], dataHolder$value)

    logHolder <- java.type("org.graalvm.demos.springr.LogHolder")
    logHolder$log(dataHolder$value, data[90:100])

    plot <- xyplot(systemLoad~time,
       data=data.frame(systemLoad = data, time = -99:0),
       main='Plot  generated by FastR running in Spring Boot',
       ylab="System load", type = c('l', 'g'), col.line='dark orange')
    print(plot)
    svg.off()
}
