# Builder
FROM container-registry.oracle.com/graalvm/native-image:25 AS nativebuild
WORKDIR /
COPY . .
RUN chmod +x mvnw
RUN ./mvnw --no-transfer-progress package -Dpackaging=native-image

# Runner: Distroless Java Base (provides glibc and required runtime libraries)
FROM gcr.io/distroless/java-base-debian13
COPY --from=nativebuild /target/hello /
EXPOSE 8080
ENTRYPOINT ["/hello"]