FROM ghcr.io/graalvm/graalvm-ce:latest
COPY build/libs/frontend-*-all.jar frontend.jar

EXPOSE 8081
CMD java -Xmn32m -XX:+UnlockExperimentalVMOptions -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar frontend.jar
