FROM ghcr.io/graalvm/graalvm-ce:latest
COPY build/libs/todo-service-*-all.jar todo-service.jar

EXPOSE 8443
CMD java -Xmn32m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar todo-service.jar
