# https://www.cloudsavvyit.com/10520/how-to-run-gui-applications-in-a-docker-container/ - latter part of the blog

ARG FULL_GRAALVM_VERSION
FROM graalvm/demos:${FULL_GRAALVM_VERSION}

# Install xterm in order to be able to access it when running GUI apps
RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
       x11vnc xvfb xterm \
       xfonts-75dpi xfonts-100dpi xfonts-base \
       libfontconfig1 libxrender1 libxtst6 \
       openssl libssl-dev libgomp1 \
       zlib1g liblzma5 libc6 libbz2-1.0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*

# https://askubuntu.com/questions/161652/how-to-change-the-default-font-size-of-xterm#161704
RUN echo "exec xterm -maximized -fa 'Monospace' -fs 18" > \
         ~/.xinitrc && chmod +x ~/.xinitrc
RUN echo ""; echo "Contents of ~/.xinitrc"; echo ""; cat ~/.xinitrc; echo "";
RUN echo "xterm*font:     *-Monospace-*-*-*-18-*" > ~/.Xresources
RUN echo ""; echo "Contents of ~/.Xresources"; echo ""; cat ~/.Xresources; echo "";

# Necessary for TruffleRuby/ruby gem installation process
# The fixes missing SO library errors we get for libssl.so.nn and libcrypto.so.nn, alternatively you can run https://github.com/oracle/truffleruby/blob/master/lib/truffle/post_install_hook.sh
RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 /usr/lib/x86_64-linux-gnu/libssl.so.10
RUN ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 /usr/lib/x86_64-linux-gnu/libcrypto.so.10

# Adding environment variable to support older demos that rely on the GRAALVM_DIR env variable
ENV GRAALVM_DIR=${JAVA_HOME}
RUN echo "GRAALVM_DIR=${GRAALVM_DIR}"

LABEL maintainer="GraalVM team"
LABEL example_git_repo="https://github.com/graalvm/graalvm-demos"
LABEL graalvm_version=${FULL_GRAALVM_VERSION}
LABEL version=${FULL_GRAALVM_VERSION}

# manual: https://linux.die.net/man/1/x11vnc
CMD ["x11vnc", "-create", "-forever", "-geometry", "1024x768"]