name: archive/javagdbnative
on:
  push:
    paths:
      - 'archive/javagdbnative/**'
      - '.github/workflows/archive-javagdbnative.yml'
  pull_request:
    paths:
      - 'archive/javagdbnative/**'
      - '.github/workflows/archive-javagdbnative.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'archive/javagdbnative'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Run 'archive/javagdbnative'
        run: |
          cd archive/javagdbnative
          mvn -Pnative -DskipTests --no-transfer-progress package
          ./target/javagdb
