name: archive/class-initialization-examples
on:
  push:
    paths:
      - 'archive/class-initialization-examples/**'
      - '.github/workflows/archive-class-initialization-examples.yml'
  pull_request:
    paths:
      - 'archive/class-initialization-examples/**'
      - '.github/workflows/archive-class-initialization-examples.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'archive/class-initialization-examples'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Run 'configure-at-runtime-example'
        run: |
          cd archive/class-initialization-examples/configure-at-runtime-example
          mvn --no-transfer-progress package
          ./target/runtime-example
      - name: Run 'configure-at-buildtime-example'
        run: |
          cd archive/class-initialization-examples/configure-at-buildtime-example
          mvn --no-transfer-progress package
          ./target/buildtime-example
