name: archive/espresso-jshell
on:
  push:
    paths:
      - 'archive/espresso-jshell/**'
      - '.github/workflows/archive-espresso-jshell.yml'
  pull_request:
    paths:
      - 'archive/espresso-jshell/**'
      - '.github/workflows/archive-espresso-jshell.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'archive/espresso-jshell'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          components: 'espresso'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'archive/espresso-jshell
        run: |
          cd archive/espresso-jshell
          ./build-espresso-jshell.sh
          echo "Math.PI" | ./espresso-jshell
