name: clouds/native-oci-generative-ai
on:
  push:
    paths:
      - 'native-image/clouds/native-oci-generative-ai/**'
      - '.github/workflows/clouds-native-oci-generative-ai.yml'
  pull_request:
    paths:
      - 'native-image/clouds/native-oci-generative-ai/**'
      - '.github/workflows/clouds-native-oci-generative-ai.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'clouds/native-oci-generative-ai'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'native-oci-generative-ai'
        run: |
          cd native-image/clouds/native-oci-generative-ai
          mvn --batch-mode clean package -Pnative
