name: java-simple-stream-benchmark
on:
  push:
    paths:
      - 'java-simple-stream-benchmark/**'
      - '.github/workflows/java-simple-stream-benchmark.yml'
  pull_request:
    paths:
      - 'java-simple-stream-benchmark/**'
      - '.github/workflows/java-simple-stream-benchmark.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'java-simple-stream-benchmark'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [latest, dev]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Run 'java-simple-stream-benchmark'
        run: |
          cd java-simple-stream-benchmark
          ./build.sh
          ./run.sh
