name: javagdbnative
on:
  push:
    paths:
      - 'javagdbnative/**'
      - '.github/workflows/javagdbnative.yml'
  pull_request:
    paths:
      - 'javagdbnative/**'
      - '.github/workflows/javagdbnative.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write # for `native-image-pr-reports` option
jobs:
  run:
    name: Run 'javagdbnative'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
      - name: Run 'javagdbnative'
        run: |
          cd javagdbnative
          mvn -Pnative -DskipTests --no-transfer-progress package
          ./target/javagdb
