name: microservices/micronaut-hello-rest-gradle
on:
  push:
    paths:
      - 'native-image/microservices/micronaut-hello-rest-gradle/**'
      - '.github/workflows/microservices-micronaut-hello-rest-gradle.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'microservices/micronaut-hello-rest-gradle'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
          native-image-job-reports: 'true'
      - name: Run 'microservices/micronaut-hello-rest-gradle'
        run: |
          cd native-image/microservices/micronaut-hello-rest-gradle
          # Test on Oracle GraalVM
          ./run.sh

          # Docker: Default Containers
          ./gradlew dockerBuild
          container_id=$(docker run --rm -d -p8081:8080 hello:latest)
          sleep 5
          docker ps
          curl "http://localhost:8081/"
          docker kill $container_id
          docker ps

          ./gradlew dockerBuildNative
          container_id=$(docker run --rm -d -p8082:8080 hello:latest)
          sleep 5
          docker ps
          curl "http://localhost:8082/"
          docker kill $container_id
          docker ps

          # Docker: Custom Containers
          docker build --no-cache . -f Dockerfile.jvm -t micronaut:hello
          container_id=$(docker run --rm -d -p8083:8080 micronaut:hello)
          sleep 5
          docker ps
          curl "http://localhost:8083/"
          docker kill $container_id
          docker ps

          docker build --no-cache . -f Dockerfile.native -t micronaut:hello
          container_id=$(docker run --rm -d -p8084:8080 micronaut:hello)
          sleep 5
          docker ps
          curl "http://localhost:8084/"
          docker kill $container_id
          docker ps

          docker images | grep micronaut
