name: microservices/micronaut-hello-rest-maven
on:
  push:
    paths:
      - 'native-image/microservices/micronaut-hello-rest-maven/**'
      - '.github/workflows/microservices-micronaut-hello-rest-maven.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'microservices/micronaut-hello-rest-maven'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        java-version: ['25']
    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Run 'microservices/micronaut-hello-rest-maven'
        run: |
          cd native-image/microservices/micronaut-hello-rest-maven
          # Test on Oracle GraalVM
          ./run.sh

          # Docker: Build and Test a JAR
          docker build --no-cache . -f Dockerfile.jvm -t micronaut:hello.jvm
          container_id=$(docker run --rm -d -p8081:8080 micronaut:hello.jvm)
          sleep 10
          docker ps
          curl "http://localhost:8081/"
          docker kill $container_id
          docker ps

          # Docker: Build and Test a native image
          docker build --no-cache . -f Dockerfile.native -t micronaut:hello
          container_id=$(docker run --rm -d -p8082:8080 micronaut:hello)
          sleep 10
          docker ps
          curl "http://localhost:8082/"
          docker kill $container_id
          docker ps

          docker images | grep micronaut