name: native-build-tools-gradle
on:
  push:
    paths:
      - 'native-image/native-build-tools/gradle-plugin/**'
      - '.github/workflows/native-build-tools-gradle.yml'
  pull_request:
    paths:
      - 'native-image/native-build-tools/gradle-plugin/**'
      - '.github/workflows/native-build-tools-gradle.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'native-build-tools-gradle'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'native-build-tools-gradle'
        run: |
          cd native-image/native-build-tools/gradle-plugin
          ./run.sh