name: native-image-logging-examples
on:
  push:
    paths:
      - 'native-image-logging-examples/**'
      - '.github/workflows/native-image-logging-examples.yml'
  pull_request:
    paths:
      - 'native-image-logging-examples/**'
      - '.github/workflows/native-image-logging-examples.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'native-image-logging-examples'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [latest, dev]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Run 'native-image-logging-examples'
        run: |
          cd native-image-logging-examples
          javac LoggerBuildTimeInit.java
          native-image LoggerBuildTimeInit --initialize-at-build-time=LoggerBuildTimeInit
          ./loggerbuildtimeinit
          javac LoggerRunTimeInit.java
          native-image LoggerRunTimeInit -H:IncludeResources="logging.properties"
          ./loggerruntimeinit
