name: native-image-configure-examples
on:
  push:
    paths:
      - 'native-image-configure-examples/**'
      - '.github/workflows/native-image-configure-examples.yml'
  pull_request:
    paths:
      - 'native-image-configure-examples/**'
      - '.github/workflows/native-image-configure-examples.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'native-image-configure-examples'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        java-version: ['17', 'dev']
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Run 'configure-at-runtime-example'
        run: |
          cd native-image-configure-examples/configure-at-runtime-example
          mvn --no-transfer-progress package
          ./target/example
      - name: Run 'configure-at-buildtime-example'
        run: |
          cd native-image-configure-examples/configure-at-buildtime-example
          mvn --no-transfer-progress package
          ./target/example
