name: native-image/hello-world
on:
  push:
    paths:
      - 'native-image/hello-world/**'
      - '.github/workflows/native-image-hello-world.yml.yml'
  pull_request:
    paths:
      - 'native-image/hello-world/**'
      - '.github/workflows/native-image-hello-world.yml.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'native-image/hello-world'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        java-version: ['25', '26-ea']
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Run 'native-image/hello-world'
        run: |
          cd native-image/hello-world
          ./run.sh