name: polyglot-javascript-java-r
on:
  push:
    paths:
      - 'polyglot-javascript-java-r/**'
      - '.github/workflows/polyglot-javascript-java-r.yml'
  pull_request:
    paths:
      - 'polyglot-javascript-java-r/**'
      - '.github/workflows/polyglot-javascript-java-r.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'polyglot-javascript-java-r'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '11'
          components: 'nodejs,R'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'polyglot-javascript-java-r'
        run: |
          cd polyglot-javascript-java-r
          npm install
          $GRAALVM_HOME/bin/node --jvm --polyglot server.js &
          sleep 10
          curl http://localhost:3000/
