name: archive/polyglot-debug
on:
  push:
    paths:
      - 'archive/polyglot-debug/**'
      - '.github/workflows/polyglot-debug.yml'
  pull_request:
    paths:
      - 'archive/polyglot-debug/**'
      - '.github/workflows/polyglot-debug.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'polyglot-debug'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Run 'polyglot-debug'
        run: |
          cd archive/polyglot-debug
          mvn --no-transfer-progress clean package
          mvn exec:exec