name: archive/polyglot-chat-app
on:
  push:
    paths:
      - 'archive/polyglot-chat-app/**'
      - '.github/workflows/polyglot-chat-app.yml'
  pull_request:
    paths:
      - 'archive/polyglot-chat-app/**'
      - '.github/workflows/polyglot-chat-app.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'polyglot-chat-app'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Run 'polyglot-chat-app'
        run: |
          cd archive/polyglot-chat-app
          ./gradlew build # pre-build application
          ./gradlew run &
          sleep 10
          curl http://localhost:12345/
